# Generated by Django 6.1.1 on 2026-09-16 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_passwordresetrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='reset_token_hash',
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
    ]
