# Generated by Django 6.1.1 on 2026-09-03 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount', models.PositiveIntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('reviews', models.PositiveIntegerField(default=0)),
                ('category', models.CharField(choices=[('Gaming', 'Gaming'), ('Home', 'Home'), ('Fashion', 'Fashion'), ('Electronics', 'Electronics'), ('Pets', 'Pets'), ('Beauty', 'Beauty'), ('Toys', 'Toys'), ('Sports', 'Sports'), ('Health', 'Health'), ('Medicine', 'Medicine'), ("Men's Fashion", "Men's Fashion"), ("Woman's Fashion", "Woman's Fashion")], max_length=30)),
            ],
        ),
    ]
