# Generated by Django 6.1.1 on 2026-09-09 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('white', 'Oq (White)'), ('black', 'Qora (Black)'), ('gray', 'Kulrang (Gray)'), ('brown', 'Jigarrang (Brown)'), ('red', 'Qizil (Red)'), ('yellow', 'Sariq (Yellow)'), ('orange', 'Olovrang (Orange)'), ('pink', 'Pushti (Pink)'), ('blue', 'Koʻk (Blue)'), ('green', 'Yashil (Green)'), ('purple', 'Binafsha (Purple)'), ('cyan', 'Havorang (Cyan)'), ('lime', 'Och yashil (Lime)'), ('gold', 'Tilla rang (Gold)'), ('burgundy', 'Bordo (Burgundy)'), ('navy', 'Toʻq koʻk (Navy)')], max_length=50, unique=True)),
                ('hex_code', models.CharField(default='#000000', max_length=7)),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Colors',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Gaming', 'Gaming'), ('Home', 'Home'), ('Fashion', 'Fashion'), ('Electronics', 'Electronics'), ('Pets', 'Pets'), ('Beauty', 'Beauty'), ('Toys', 'Toys'), ('Sports', 'Sports'), ('Health', 'Health'), ('Medicine', 'Medicine'), ("Men's Fashion", "Men's Fashion"), ("Woman's Fashion", "Woman's Fashion"), ('Smartphone', 'Smartphone'), ('Monitor', 'Monitor'), ('Watch', 'Watch'), ('Camera', 'Camera'), ('Headphones', 'Headphones'), ('Gamepad', 'Gamepad'), ('Shirt', 'Shirt'), ('Tablet', 'Tablet'), ('Laptop', 'Laptop'), ('Speaker', 'Speaker'), ('Keyboard', 'Keyboard'), ('Mouse', 'Mouse'), ('Footwear', 'Footwear'), ('Safety Gear', 'Safety Gear'), ('Eyewear', 'Eyewear'), ('Bags', 'Bags'), ('Jewelry', 'Jewelry')], max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.color'),
        ),
    ]
