# Generated by Django 6.1.1 on 2026-09-11 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sale_end_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_start_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
