# Generated by Django 6.1.1 on 2026-09-11 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_sale_end_at_product_sale_start_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sale_start_at',
        ),
    ]
